name: Theresa Crowley
favicon: null
layout_spectrum: 0.216
typography_spectrum: 0.750550240278244
title: 'Live, Love, Talk'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#68c1e9'
    - '#361f11'
    - '#fdfe00'
    - '#c98f46'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
