name: Theresa Crowley
favicon: null
layout_spectrum: 0.216
typography_spectrum: 0.750550240278244
title: 'Live, Love, Talk'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5f0e8'
    - '#8fbcff'
    - '#cf85ff'
    - '#e1c7a2'
    - '#677264'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
