name: Theresa Crowley
favicon: null
layout_spectrum: 0.216
typography_spectrum: 0.750550240278244
title: 'Live, Love, Talk'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4efe9'
    - '#2077c6'
    - '#090e0a'
    - '#c9c1aa'
    - '#596e25'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
